DROP TABLE IF EXISTS KINGDOM;
CREATE TABLE KINGDOM (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CODE STRING UNIQUE NOT NULL,
	NAME STRING NOT NULL
);

DROP TABLE IF EXISTS INDEX_;
CREATE TABLE INDEX_ (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	VALUE STRING UNIQUE NOT NULL
);

DROP TABLE IF EXISTS TAG;
CREATE TABLE TAG (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING UNIQUE NOT NULL,
	EXPLAINTION TEXT
);

/**
 *	NAME PATTERN: [NAME_LOCALE] (exam: en)
 *	VALUE PATTERN: NAME_LOCALE::VALUE_LOCALE (exam: root)
 */
DROP TABLE IF EXISTS LOCALES;
CREATE TABLE LOCALES (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING NOT NULL,
	VALUE STRING
);

/**
 *	LOCALE IDS SPEARATE BY SYMBOL '::' (exam: 1::5::15::9)
 */
DROP TABLE IF EXISTS FAMILY;
CREATE TABLE FAMILY (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	KINGDOM_ID INTEGER NOT NULL,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	DESCRIPTION TEXT,
	AVATAR STRING,
	FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);

/*
 *	SAME AS FAMILY
 */
DROP TABLE IF EXISTS GENUS;
CREATE TABLE GENUS (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	KINGDOM_ID INTEGER NOT NULL,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	DESCRIPTION TEXT,
	AVATAR STRING,
	FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);

/**
 *	LOCALE IDS SPEARATE BY SYMBOL '::' (exam: 1::5::15::9)
 */
DROP TABLE IF EXISTS GLOSSARY;
CREATE TABLE GLOSSARY (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	EXPLAINTION TEXT,
	EXAMPLE TEXT
);

/*
DROP TABLE IF EXISTS [OBJECT];
CREATE TABLE [OBJECT]
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   NAME STRING NOT NULL,
   KINGDOM_ID INTEGER NOT NULL,
   FAMILY_IDS STRING,
   GENUS_IDS STRING,    
   FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);
*/

/**
 * INIT KINGDOM DATA
 */
INSERT INTO KINGDOM VALUES(NULL, 'B', 'Botanical');
INSERT INTO KINGDOM VALUES(NULL, 'Z', 'Zoological');


