INSERT INTO [Tag] VALUES (NULL, 'bee-keeping', ' ');
INSERT INTO [Tag] VALUES (NULL, 'handicraft', ' ');
INSERT INTO [Tag] VALUES (NULL, 'fuelwood', ' ');
INSERT INTO [Tag] VALUES (NULL, 'charcoal', ' ');
INSERT INTO [Tag] VALUES (NULL, 'med.', 'medicinal');
INSERT INTO [Tag] VALUES (NULL, 'natl symb:', 'national symbol');
INSERT INTO [Tag] VALUES (NULL, 'relig.:', 'religious significance');
INSERT INTO [Tag] VALUES (NULL, 'refor.', 'planted for reforestation');
INSERT INTO [Tag] VALUES (NULL, 'cult.', 'cultivated, cultured');
INSERT INTO [Tag] VALUES (NULL, 'expl.', 'exploited');
INSERT INTO [Tag] VALUES (NULL, 'hybr.', 'hybrid, hybridized');
INSERT INTO [Tag] VALUES (NULL, '(timber)', 'use: wood');
INSERT INTO [Tag] VALUES (NULL, 'constr.', 'construction');
INSERT INTO [Tag] VALUES (NULL, 'insecticide', ' ');
INSERT INTO [Tag] VALUES (NULL, 'roofing', ' ');
INSERT INTO [Tag] VALUES (NULL, 'shade', 'planted to provide shade for roads...');
INSERT INTO [Tag] VALUES (NULL, 'hedge', ' ');
INSERT INTO [Tag] VALUES (NULL, 'spice', 'used as a spice');
INSERT INTO [Tag] VALUES (NULL, 'resin', ' ');
INSERT INTO [Tag] VALUES (NULL, 'delicacy', ' ');
INSERT INTO [Tag] VALUES (NULL, 'E', 'endangered');
INSERT INTO [Tag] VALUES (NULL, 'T', 'threatened');
INSERT INTO [Tag] VALUES (NULL, 'endemic', ' ');
INSERT INTO [Tag] VALUES (NULL, 'green manure', ' ');
INSERT INTO [Tag] VALUES (NULL, 'stuffing', 'used to stuff pillows etc.');
INSERT INTO [Tag] VALUES (NULL, 'utensil', ' ');
INSERT INTO [Tag] VALUES (NULL, 'Pr.', 'protected');
INSERT INTO [Tag] VALUES (NULL, 'edible', 'consumed, not extensively');
INSERT INTO [Tag] VALUES (NULL, 'pet', ' ');
INSERT INTO [Tag] VALUES (NULL, 'fiber', ' ');
INSERT INTO [Tag] VALUES (NULL, 'garden', 'also: ornamental / hedge');
INSERT INTO [Tag] VALUES (NULL, 'pulp', 'used to make paper');
INSERT INTO [Tag] VALUES (NULL, 'narcotic', ' ');
INSERT INTO [Tag] VALUES (NULL, 'nw pr.', 'non-wood products');
INSERT INTO [Tag] VALUES (NULL, 'ind.', 'industrial');
INSERT INTO [Tag] VALUES (NULL, 'veg.', 'vegetable');
INSERT INTO [Tag] VALUES (NULL, 'pois.', 'poisonous, toxic');
INSERT INTO [Tag] VALUES (NULL, 'grafting', 'used in grafting 2 species on same plant');
INSERT INTO [Tag] VALUES (NULL, 'latex', ' ');
INSERT INTO [Tag] VALUES (NULL, 'oil', ' ');
INSERT INTO [Tag] VALUES (NULL, 'essence', ' ');
INSERT INTO [Tag] VALUES (NULL, 'fish pois.', 'used as fish poison');
INSERT INTO [Tag] VALUES (NULL, 'syn:', 'synonym');
INSERT INTO [Tag] VALUES (NULL, 'lawn', ' ');
INSERT INTO [Tag] VALUES (NULL, 'wood', 'provide wood, timber');
INSERT INTO [Tag] VALUES (NULL, 'soil conserv.', 'soil conservation');
INSERT INTO [Tag] VALUES (NULL, 'firebreak', ' ');
INSERT INTO [Tag] VALUES (NULL, 'fodder', ' ');
INSERT INTO [Tag] VALUES (NULL, 'tanning', ' ');
INSERT INTO [Tag] VALUES (NULL, 'roadside', 'roadsides as habitats; see: shade');
INSERT INTO [Tag] VALUES (NULL, 'dyeing', ' ');
INSERT INTO [Tag] VALUES (NULL, 'food', 'used extensively as food');
INSERT INTO [Tag] VALUES (NULL, 'vector', 'disease carrier');
INSERT INTO [Tag] VALUES (NULL, 'comm.', 'commercial, sold on large scale');
INSERT INTO [Tag] VALUES (NULL, 'world:', 'global situation');
INSERT INTO [Tag] VALUES (NULL, 'meat', ' ');
INSERT INTO [Tag] VALUES (NULL, 'tealeaf', 'used in tealeaf flavoring');
INSERT INTO [Tag] VALUES (NULL, 'bonsai', 'used to make bonsai');
INSERT INTO [Tag] VALUES (NULL, 'silkworm', ' ');
INSERT INTO [Tag] VALUES (NULL, 'dike prot.', 'dike protection');
INSERT INTO [Tag] VALUES (NULL, 'pest', 'unwanted, undesirable');
INSERT INTO [Tag] VALUES (NULL, 'distillation', 'alcoho- making');
INSERT INTO [Tag] VALUES (NULL, 'breeding', 'used for breeding varieties');
INSERT INTO [Tag] VALUES (NULL, 'obs.', 'observed');
INSERT INTO [Tag] VALUES (NULL, 'orn.', 'ornamental');
INSERT INTO [Tag] VALUES (NULL, 'crossing', 'crossed, used in crossing');
INSERT INTO [Tag] VALUES (NULL, 'cut flower', ' ');
INSERT INTO [Tag] VALUES (NULL, 'perfume', ' ');
INSERT INTO [Tag] VALUES (NULL, 'extract', ' ');
INSERT INTO [Tag] VALUES (NULL, '(carving)', 'use: handicraft');
INSERT INTO [Tag] VALUES (NULL, '(threatened)', 'use: rare');
INSERT INTO [Tag] VALUES (NULL, 'precious', 'rare, endangered, threatened, vulnerable');
INSERT INTO [Tag] VALUES (NULL, 'leather', ' ');
INSERT INTO [Tag] VALUES (NULL, '(hide)', 'use: leather');
INSERT INTO [Tag] VALUES (NULL, 'souvenir', 'collected as souvenir');
INSERT INTO [Tag] VALUES (NULL, 'coastal', ' ');
INSERT INTO [Tag] VALUES (NULL, 'mangrove', ' ');
INSERT INTO [Tag] VALUES (NULL, 'settlement', 'occurs near human settlements');
INSERT INTO [Tag] VALUES (NULL, 'seasoning', 'food seasoning, flavoring');
INSERT INTO [Tag] VALUES (NULL, 'paddy', 'paddy fields as habitats');
INSERT INTO [Tag] VALUES (NULL, 'plantation shade', 'shading trees for tea, coffee trees...');
INSERT INTO [Tag] VALUES (NULL, 'appliance', ' ');
INSERT INTO [Tag] VALUES (NULL, 'natl. flow.', 'national flower');
INSERT INTO [Tag] VALUES (NULL, 'indi.', 'indicator');
INSERT INTO [Tag] VALUES (NULL, 'furniture', ' ');
INSERT INTO [Tag] VALUES (NULL, 'lac insect', 'for sticklac used in industry, medicine');
INSERT INTO [Tag] VALUES (NULL, 'wildlife trade', ' ');
INSERT INTO [Tag] VALUES (NULL, 'in-house', ' ');
INSERT INTO [Tag] VALUES (NULL, 'urban', 'cities and towns as habitats');
INSERT INTO [Tag] VALUES (NULL, 'Rs.', 'preserved');
INSERT INTO [Tag] VALUES (NULL, '(firewood)', 'use: fuelwood');
