DROP TABLE IF EXISTS [Kingdom];
CREATE TABLE [Kingdom] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	CODE STRING UNIQUE NOT NULL,
	NAME STRING NOT NULL
);

DROP TABLE IF EXISTS [Index];
CREATE TABLE [Index] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	VALUE STRING UNIQUE NOT NULL
);

DROP TABLE IF EXISTS [Tag];
CREATE TABLE [Tag] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING UNIQUE NOT NULL,
	EXPLAINTION STRING
);

/**
 *	NAME PATTERN: [NAME_LOCALE] (exam: en)
 *	VALUE PATTERN: NAME_LOCALE::VALUE_LOCALE (exam: root)
 */
DROP TABLE IF EXISTS [Locales];
CREATE TABLE [Locales] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING NOT NULL,
	VALUE STRING
);

/**
 *	LOCALE IDS SPEARATE BY SYMBOL '::' (exam: 1::5::15::9)
 */
DROP TABLE IF EXISTS [Family];
CREATE TABLE [Family] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	KINGDOM_ID INTEGER NOT NULL,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	DESCRIPTION STRING,
	AVATAR STRING,
	FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);

/*
 *	SAME AS FAMILY
 */
DROP TABLE IF EXISTS [Genus];
CREATE TABLE [Genus] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	KINGDOM_ID INTEGER NOT NULL,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	DESCRIPTION STRING,
	AVATAR STRING,
	VARIANT_IDS STRING,
	FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);

DROP TABLE IF EXISTS [Species];
CREATE TABLE [Species] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING NOT NULL,
	VARIANT_IDS STRING
);

/**
 *	LOCALE IDS SPEARATE BY SYMBOL '::' (exam: 1::5::15::9)
 */
DROP TABLE IF EXISTS [Glossary];
CREATE TABLE [Glossary] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	NAME STRING NOT NULL,
	LOCALE_IDS STRING,
	EXPLAINTION STRING,
	EXAMPLE STRING
);

/* TYPE = 1 AS 'S' | TYPE = 2 AS 'O' */
DROP TABLE IF EXISTS [Variant];
CREATE TABLE [Variant] (
	ID INTEGER PRIMARY KEY AUTOINCREMENT,
	VALUE STRING,
	TYPE NUMERIC	
);

/* EN_NAMES and VN_NAMES contain multi value and separate by symbol '::' */
DROP TABLE IF EXISTS [NaturalObject];
CREATE TABLE [NaturalObject]
(
   ID INTEGER PRIMARY KEY AUTOINCREMENT,
   KINGDOM_ID INTEGER NOT NULL,
   FAMILY_IDS STRING NOT NULL,
   INDEX_IDS STRING,
   GENUS_ID INTEGER NOT NULL,
   SPECIES_ID INTEGER NOT NULL,
   EN_NAMES STRING,
   VN_NAMES STRING,
   TAG_IDS STRING,
   CREATE_DATE STRING,
   MODIFIY_DATE STRING,
   REFERENCE STRING,
   DES STRING,
   AVATAR STRING,
   FOREIGN KEY (KINGDOM_ID) REFERENCES KINGDOM(ID)
);

/**
 * INIT KINGDOM DATA
 */
INSERT INTO KINGDOM VALUES(NULL, 'B', 'Botanical');
INSERT INTO KINGDOM VALUES(NULL, 'Z', 'Zoological');


