INSERT INTO [Glossary] VALUES (NULL, 'root cap', ' ', 'cap-like structure at tipcovers & protects growing point', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'meristematic zone', ' ', '(root) growing point producing new cells for root cap', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'zone of elongation', ' ', 'root zone behind growing point', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'root hair zone', ' ', 'zone where most water absortion occurs', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'zone of mature cel', ' ', '(root) zone forming bulk of rootcells not undergoing further change', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'primary', ' ', '(root) = tap root: first root formed by growth of radicle, itself vertical', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'secondary', ' ', '(root) borne on primary roothorizonal or oblique', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'adventitious', ' ', 'root system produced from any other part of plant except radicle', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', '(củ) mập');
INSERT INTO [Glossary] VALUES (NULL, 'fleshy', '1', '(root) swollen and fleshy with stored food', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'conical', ' ', 'when thread-like secondary roots found throughout length', 'carrot');
INSERT INTO [Glossary] VALUES (NULL, 'fusiform', ' ', '(root) spindle-like: thickest in middlenarrow towards base & apex', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'napiform', ' ', '(root) very thick root at basealmost spherical', 'turnip');
INSERT INTO [Glossary] VALUES (NULL, 'tuberous', ' ', '(root) not assuming any definite form', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'aerophores', ' ', '= pneumatophore', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'respitarory', ' ', '= pneumatophore', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'buttress', ' ', ' horizontal root arising jointly from base of tap root and trunk', 'rubber');
INSERT INTO [Glossary] VALUES (NULL, 'plank', ' ', '= buttress', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'reproductive', ' ', '(root) adventitious buds on tap root that can grow to form new plant', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'mycorrhizal', ' ', '(root) having fungal hyphae that help in obtaining nutriens', 'pines');
INSERT INTO [Glossary] VALUES (NULL, 'fibrous', ' ', '(root) underground in groups at base of erect stem or nodes of horiz. stem', 'grains');
INSERT INTO [Glossary] VALUES (NULL, 'fasciculated', ' ', 'roots in clusters or groups', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'dạng rẽ quạt');
INSERT INTO [Glossary] VALUES (NULL, 'palmate', '2', '(root)  branched like palm', 'some oorchids');
INSERT INTO [Glossary] VALUES (NULL, 'moniliform', ' ', '(root) swollen at regular intervals like beads of necklace', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'annulated', ' ', 'thickened root with series of ring-like outgrowths', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'stilt', ' ', '(root) short, developing obliquely from basal nodes of stem', 'maize');
INSERT INTO [Glossary] VALUES (NULL, 'brace', ' ', '= root, stilt', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pillar', ' ', '(root) pillar-like, supporting heavy horizontal branches', 'banyan');
INSERT INTO [Glossary] VALUES (NULL, 'epiphytic', ' ', '(root) thick, irregular, devoid of root cap, root hair covered by spongy tissue', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hygroscopic', ' ', '= epyphitic', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'photosynthetic', ' ', '(root) green, helping in manufacturing food, some fixed to rock', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'assimilatory', ' ', 'photosynthetic root', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'root, clinging', ' ', '= climbing', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'climbing', ' ', 'adventitious roots of climbers, hold support by clawsswollen discs or sticky juice at tip', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pulvinus', ' ', '(leaf base) swollen', 'mango');
INSERT INTO [Glossary] VALUES (NULL, 'sheating', ' ', '(leaf base) expanded, covers stem partitially or completely', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'stipules', ' ', '2 small flat green or scaly lateral outgrowths at leaf base', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cuống lá');
INSERT INTO [Glossary] VALUES (NULL, 'petiole', '3', 'stalk of leaf lifting lamina above stem', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'adaxial', ' ', 'leaf upper surface', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'abaxial', ' ', 'leaf lower surface', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình mạng');
INSERT INTO [Glossary] VALUES (NULL, 'reticulate', '4', 'veins forming reticulum see: network', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pinnate', ' ', '(leaf veins) with one midrib gives off lateral veins', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'unicostate', ' ', '= pinnate', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'dạng rẽ quạt');
INSERT INTO [Glossary] VALUES (NULL, 'palmate', '5', '(leaf veins) with many equally strong veins from tip of petiole', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'convergent', ' ', '(leaf veins) with ribs convergING towards apex', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'divergent', ' ', '(leaf veins) with ribs diverge outwards from petiole tip towards margins', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'số thứ diệp lẻ');
INSERT INTO [Glossary] VALUES (NULL, 'imparipinnate', '6', '(leaf) when pinane odd in number', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'bipinnate', ' ', 'leaf divided twice', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'thứ diệp / lá phụ cấp 2');
INSERT INTO [Glossary] VALUES (NULL, 'pinnae', '7', 'leaflets of bipinnate leaf', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tam diệp / lá phụ cấp 2');
INSERT INTO [Glossary] VALUES (NULL, 'pinnules', '8', 'leaflets of tripinnate leaf', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'sóng lá');
INSERT INTO [Glossary] VALUES (NULL, 'rachis', '9', 'axis of pinnae', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'rachilla', ' ', 'axix of pinnule', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'rachule', ' ', '= rachilla', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tam diệp');
INSERT INTO [Glossary] VALUES (NULL, 'tripinnate', '10', '(leaf) divided thrice', 'Melia azedarach');
INSERT INTO [Glossary] VALUES (NULL, 'decompound', ' ', '(leaf) divided more than thrize', 'carrot');
INSERT INTO [Glossary] VALUES (NULL, 'palmate compound', ' ', 'when petiole bears leaflets at its tip', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'multifoliolate', ' ', '(leaf) divided into 5 or more leaflets', 'Bombax');
INSERT INTO [Glossary] VALUES (NULL, 'digitate', ' ', '= multifoliate', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ternate', ' ', '= trifoliolate', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'binate', ' ', '2 leaflets side by side', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'unifoliolate', ' ', 'single leaflet separate from petiole by constriction', 'Citrus');
INSERT INTO [Glossary] VALUES (NULL, 'interpetiolar', ' ', 'when adjacent stipules of 2 leaves fuse together, appearing in between 2 petioles', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'petiolar', ' ', 'when stipules united with petiole for some distance, appear as 2 small basal wings', 'rose');
INSERT INTO [Glossary] VALUES (NULL, 'ochreate', ' ', 'when stipules fused on both outer & inner margins to form sheath around stem', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'bud scale', ' ', '(leaf) stipules of young leaves fused to form large scale, fall down as leaves unfold', 'banyan');
INSERT INTO [Glossary] VALUES (NULL, 'stipule, foliaceous', ' ', '(stipule) large & green, look like leaves', 'pea');
INSERT INTO [Glossary] VALUES (NULL, 'stipular spine', ' ', 'stipules transformed into spines', 'Acacia');
INSERT INTO [Glossary] VALUES (NULL, 'stipular tendril', ' ', 'stipules modified to tendrils', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'herbaceous', ' ', '(lamina) soft, thin & pliable', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'succulent', ' ', 'thick & fleshy', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'coriaceous', ' ', '(lamina) leathery, thich & tough', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', '(phiến lá) láng bóng');
INSERT INTO [Glossary] VALUES (NULL, 'glaucous', '11', '(lamina) shiny & smooth', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', '(phiến lá) láng mờ');
INSERT INTO [Glossary] VALUES (NULL, 'glabrous', '12', '(lamina) smooth but dull', 'eucalyptus leaf');
INSERT INTO [Glossary] VALUES (NULL, 'sub-glabrous', ' ', 'glabrous with few hairs', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'nhám');
INSERT INTO [Glossary] VALUES (NULL, 'scabrous', '13', 'rough to touch', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'spinous', ' ', '(lamina) spiny', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'glutinous', ' ', '(lamina) covered with sticky substance', 'tobacco leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'nhăn');
INSERT INTO [Glossary] VALUES (NULL, 'rugose', '14', 'wrinkled', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'mealy', ' ', '(lamina) covered with small scales or powder of wax', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pubescent', ' ', '(hairs) short & soft', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pilose', ' ', '(hairs) long & scattered', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'dày & rậm');
INSERT INTO [Glossary] VALUES (NULL, 'villous', '15', '(hairs) long, soft, dense', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'tomentose', ' ', '(hairs) soft but tangled', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hirsute', ' ', '(hairs) stiff but fine', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hispid', ' ', '(hairs) bristly', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'floccose', ' ', 'hairs forming detachable locks', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ổc', ' ', 'hairs on margins', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', '(phiến) hình kim');
INSERT INTO [Glossary] VALUES (NULL, 'acicular', '16', '(lamina) needdle-shaped', 'pines leaves');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình hẹp');
INSERT INTO [Glossary] VALUES (NULL, 'linear', '17', '(lamina) long, narrow & flat', 'grass leaves');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình giáo');
INSERT INTO [Glossary] VALUES (NULL, 'lanceolate', '18', '(lamina) more tapering towards apexless towards base', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình giáo ngược');
INSERT INTO [Glossary] VALUES (NULL, 'oblanceolate', '19', 'lanceolate reverse: more tapering towards base', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình trái xoan');
INSERT INTO [Glossary] VALUES (NULL, 'elliptic', '20', 'L=1.5-2W, apex and base tapering in the same way, widest point at middle', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình trứng, đáy rộng');
INSERT INTO [Glossary] VALUES (NULL, 'ovate', '21', 'egg-shaped: round at base, tapering towards apex', 'banyan leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình trứng ngược, đáy hẹ');
INSERT INTO [Glossary] VALUES (NULL, 'obovate', '22', 'ovate reverse: round at apex, tapering towards base', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'subulate', ' ', 'longnarrow & tapering from base to apex', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tròn dài');
INSERT INTO [Glossary] VALUES (NULL, 'oblong', '23', 'almost rectangular, with 2 margins in parallel', 'banana leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phiến hình bánh bò');
INSERT INTO [Glossary] VALUES (NULL, 'rhomboid', '24', '4 sides, with 2 sides of opposite halves in parallel', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'rhombate', ' ', '= rhomboid', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình tim');
INSERT INTO [Glossary] VALUES (NULL, 'cordate', '25', '(lamina) heart-shaped, like ovate but base notched', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình tim ngược');
INSERT INTO [Glossary] VALUES (NULL, 'obcordate', '26', 'cordate reverse: heart-shaped with apex notched', 'Bauhinia leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'gần như hình tròn');
INSERT INTO [Glossary] VALUES (NULL, 'orbicular', '27', 'almost round', 'lotus leaf');
INSERT INTO [Glossary] VALUES (NULL, 'rotund', ' ', '= orbicular', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'reniform', ' ', 'kidney-shaped', 'Centella asiatica');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình lưỡi liềm');
INSERT INTO [Glossary] VALUES (NULL, 'unate', '28', 'sickled-shaped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'spatulate', ' ', 'spoon-shaped: round at apex & narrow towards base', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cuneate', ' ', '(lamina) wedge-shaped', 'Pistia leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phiến hình tam giác');
INSERT INTO [Glossary] VALUES (NULL, 'deltoid', '29', '(lamina) triangular', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phiến hình mũi tên');
INSERT INTO [Glossary] VALUES (NULL, 'hastate', '30', '(lamina) arrowhead-shaped with 2 lobes pointing outwards', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình đầu tên');
INSERT INTO [Glossary] VALUES (NULL, 'sagittate', '31', 'arrowhead-shaped with 2 lobes pointing inwards', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình đàn lyre');
INSERT INTO [Glossary] VALUES (NULL, 'lyrate', '32', 'lyre-shaped terminal lobes large & round, lateral lobes smaller towards base', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'runcinate', ' ', '(lamina) terminal lobe large & pointed; smaller lobes pointed towards base', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', '2 thùy bất xứng');
INSERT INTO [Glossary] VALUES (NULL, 'oblique', '33', '2 halves unequal', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'falcate', ' ', '(lamina) flat & narrow sickle-shaped', 'eucalyptus leaf');
INSERT INTO [Glossary] VALUES (NULL, 'sinuate', ' ', '(margin) deeply undulated', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'rìa răng cưa');
INSERT INTO [Glossary] VALUES (NULL, 'serrate', '34', '(margin) toothed, teeth directed upwards', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'biserrate', ' ', '(margin) serrate with each tooth toothed again (castor)', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'dentate', ' ', '(margin) serrate with teeth directed outwards', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'retroserrate', ' ', '(margin) = runcinateserrate, with teeth directed backward', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'rìa răng tròn');
INSERT INTO [Glossary] VALUES (NULL, 'crenate', '35', '(margin) with teeth rounded', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'lobed', ' ', '(margin) incised with incisions more than size of teeth', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tù');
INSERT INTO [Glossary] VALUES (NULL, 'obtuse', '36', 'slightly rounded', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'nhọn');
INSERT INTO [Glossary] VALUES (NULL, 'acute', '37', 'pointed, 2 straight margins forming acute angle', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tận cùng bằng đuôi');
INSERT INTO [Glossary] VALUES (NULL, 'caudate', '38', 'pointed & drawn out like a tail', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tận cùng bằng mũi');
INSERT INTO [Glossary] VALUES (NULL, 'cuspidate', '39', 'ending in a pointed apex', 'date palm leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'có kim nhọn ngắn');
INSERT INTO [Glossary] VALUES (NULL, 'mucronate', '40', 'apex pointed suddenly from almost rounded region to have a sharp point', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'nhọn hoắt');
INSERT INTO [Glossary] VALUES (NULL, 'acuminate', '41', 'slightly elongated acute apex with tapering sides', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tận cùng bằng dây quấn');
INSERT INTO [Glossary] VALUES (NULL, 'tendrillar', '42', 'long thin sensitive & capable of coiling around a support', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cirrhose', ' ', 'having non-sensitive tendril-like apices', 'banana leaf');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cụt /  vát');
INSERT INTO [Glossary] VALUES (NULL, 'truncate', '43', 'almost flat', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tròn');
INSERT INTO [Glossary] VALUES (NULL, 'retuse', '44', 'rounded but slightly notched', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'emarginate', ' ', 'rounded but with deep notch', 'Oxalis leaf');
INSERT INTO [Glossary] VALUES (NULL, 'bracteate', ' ', 'having bracts', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ebracteate', ' ', 'having no bract', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'sessile', ' ', 'having no petiole or pedicel, leaf/flower attached directly to branch', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'thalamus', ' ', 'base of flower proper', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'torus', ' ', '= thalamus', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tràng hoa / vành');
INSERT INTO [Glossary] VALUES (NULL, 'corolla', '45', 'collective of petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'androecium', ' ', 'see: stamen', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình cái cốc');
INSERT INTO [Glossary] VALUES (NULL, 'cupulate', '46', 'cup-shaped', 'Gossypum flower');
INSERT INTO [Glossary] VALUES (NULL, 'infundibuliform', ' ', 'funnel-shaped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'globose', ' ', 'globe-like', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình ống');
INSERT INTO [Glossary] VALUES (NULL, 'tubular', '47', 'tube-like', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'bilabiate', ' ', '(corolla) 2-lipped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'saccate', ' ', '(calyx) inner sepals pouched or concave from inside', 'mustard flower');
INSERT INTO [Glossary] VALUES (NULL, 'pappus', ' ', '(calyx) formed into hairs', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'petaloid', ' ', '(calyx) colored like petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cruciform', ' ', '(corolla) 4 free unguiculate (clawed) petals at 4 corners of a cross', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'caryophyllaceous', ' ', '(corolla) 5 unguiculate petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'rosaceous', ' ', '(corolla) 5 or more free petals sessile or sub-sessile, spread out like a saucer', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'papilionaceous', ' ', '(corolla) butterfly-like', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'urceolate', ' ', 'urn-shaped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hypocrateriform', ' ', 'salver-shaped', 'Ipomaea quamoclit');
INSERT INTO [Glossary] VALUES (NULL, 'rotate', ' ', '(corolla) short tube, limbs place transversely spoke-like', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ringent', ' ', '(bilabiate) lips open', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'personate', ' ', '(bilabiate) lips close', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'spurred', ' ', 'drawn out into spur = beak-like', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ligutate', ' ', '(bilabiate) short & narrow tube below, expanded strap-like', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'corolla, aestivation', ' ', 'arrangement of petals in bud condition', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'valvate', ' ', '(aestivation) margins of petals touch each other without overlapping', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'twisted', ' ', '(aestivation) 1 margin overlaps margin of adjacent petal', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'xếp lợp');
INSERT INTO [Glossary] VALUES (NULL, 'imbricate', '48', '(aestivation, petals) evenly overlapping', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'bulb, quincuncial', ' ', 'imbricate proper', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'epipetalous', ' ', '(stamen) fused with petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'epyphyllous', ' ', '(stamen) fused with sepals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'inserted', ' ', '(stamen) projecting shorter than corolla', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'exserted', ' ', '(stamen) projecting out of corolla', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'antipetalous', ' ', '(stamen) opposite petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'polyandrous', ' ', '(stamen) free, with equal or unequal lengths', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'alternipetalous', ' ', 'common, stamens alternate with petals (common)', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'basifixed', ' ', '(anther) fixed directly at filament top', 'mustard');
INSERT INTO [Glossary] VALUES (NULL, 'innate', ' ', '= basifixed', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'adnate', ' ', '(filament) running throughout length of anther', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'dorsifixed', ' ', '(filament) filament firmly fixed to back of anther', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'versatile', ' ', '(filament) filament attached to back of anther which can swing freely', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'longitudinal', ' ', '(dehiscence) long slits lengthwise, may be laterorse, introrse or extrorse', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'laterorse', ' ', '(dehiscence) longitudinal slits on sides', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'introrse', ' ', '(dehiscence) longitudinal slits formed towards inner side or center of flower', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'extrorse', ' ', '(dehiscence) longitudinal slits lie towards outer sides of petals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'transverse', ' ', '(dehiscence) lobes burst by slits breathwise roughly in middle', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'valvular', ' ', '(dehiscence) lobes irregularly open by valves', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'irregular', ' ', '(dehiscence) anther wall breaks irregularly', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'terminal', ' ', '(carpel origin) apical, most common', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ateral', ' ', '(carpel origin) arising from 1 side of ovary', 'mango');
INSERT INTO [Glossary] VALUES (NULL, 'gynobasic', ' ', '(carpel origin) arising from midbasal part of ovary', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'monocarpellary', ' ', '(gynaecium) with 1 carpel', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'apocarpous', ' ', '(gynaecium) polycarpellary, with many free carpels', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'polycarpellary', ' ', '(gynaecium) polycarpellary, with fused carpels', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'marginal', ' ', '(placentation) in mococarpellary, ovary bears logitudinal placenta', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đính phôi trắc mô');
INSERT INTO [Glossary] VALUES (NULL, 'parietal', '49', '(placentation) 2 or more placentae attached to ovary wall. in syncarpous pistils with uniocular ovar', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đính phôi trung trục');
INSERT INTO [Glossary] VALUES (NULL, 'axile', '50', '(placentation) ovary partitioned into 2 or more chambers, placentae in center of ovary at place of u', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đính phôi trung tâm');
INSERT INTO [Glossary] VALUES (NULL, 'central', '51', '(placentation) ovules borne around central column running throughout ovary', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đính phôi từ đáy');
INSERT INTO [Glossary] VALUES (NULL, 'basal', '52', '(placentation) ovary unilocular having 1 placenta bearing 1 ovule', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đính phôi treo');
INSERT INTO [Glossary] VALUES (NULL, 'apical', '53', '(placentation) ovule attached to tip of chamber & hangs down', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'superficial', ' ', '(placentation) pistil moocarpellary or syncarpous, ovules on whole inner surface of ovary', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hypogyny', ' ', '(thalamus) thalamus below gynaecium, either convex, conical or elongated', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'perigyny', ' ', '(thalamus) thalamus periphery forms hypanthium , apex in center & bears 1 or more pistils', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'disc-shaped', ' ', '(thalamus) periginy gynaecium attached to disc center', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cup-shaped', ' ', '(thalamus) periginy gynaecium arises from cup bottom', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'flask-shaped', ' ', '(thalamus) periginy gynaecium produced from flask bottom', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'epigyny', ' ', '(thalamus) thalamus in form of hollow flask, gynaecium produced from bottom of flask', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'simple raceme', ' ', 'indefinite inflorescence, growing point remains active', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'ngù');
INSERT INTO [Glossary] VALUES (NULL, 'corymb', '54', '(inflorescence) broad flat-topped cluster, outer pedicels long, shorter toward center', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'corymbose', ' ', '(inflorescence) intermediate between raceme and corymb', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tán');
INSERT INTO [Glossary] VALUES (NULL, 'umbel', '55', 'indefinite inflorescence, peduncle suppressed, reduced to a point where flowers develop', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'involucre', ' ', '(umbel) with whorl of bracts at base of flowers', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'centripetal', ' ', '(umbel) with youngest flowers in center', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'gié / hoa tự hình bông');
INSERT INTO [Glossary] VALUES (NULL, 'spike', '56', 'flowers sessile, peduncle elongated , sessile flowers attached directly to a common axis', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'spikelet', ' ', 'flowers sessile, small, few-flowered spikes surrounded at base by two glumes (scales)', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'catkin', ' ', '(inflorescence) flowers sessile, peduncle elongated, compact, unisexual spike', 'oak,');
INSERT INTO [Glossary] VALUES (NULL, 'amentum', ' ', '= catkin', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'capitulum', ' ', 'indefinite inflorescence, peduncle compressed to convex upright column, or receptacle', 'concave disc');
INSERT INTO [Glossary] VALUES (NULL, 'racemose head', ' ', '= capitulum', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hoa ống');
INSERT INTO [Glossary] VALUES (NULL, 'tubular', '57', '(floret) capitulum with petals form a tube', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hoa môi');
INSERT INTO [Glossary] VALUES (NULL, 'ligulate', '58', '(floret) capitulum with petals form tongue-shaped structure', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'homogamous', ' ', '(capitulum) only one type of petal form (florets) exists', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'heterogamous', ' ', '(capitulum) both types of petal form (florets) exist', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'hypanthodium', ' ', '(inflorescence) peduncle flattened, flask-shaped fleshy receptacle', 'Ficus');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'xim');
INSERT INTO [Glossary] VALUES (NULL, 'cyme', '59', 'definite inflorescence, growing point used up to form a flower', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'helicoid', ' ', '(cyme) uniparous, successive lateral branches arise on same side, so flowers borne only on 1 si', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'scorpioid', ' ', '(cyme) uniparous cyme, flowers borned alternately on both sides', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'biparous', ' ', '(cyme) main axis ends in flower, two lateral branches also end in lateral flowers', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'dichasial cyme', ' ', '= biparous', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'multiparous', ' ', '(cyme) more than 2 lateral branches continue inflorescence growth, parent axis ends in flower', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'polychasial', ' ', '= multiparous', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cymode head', ' ', 'formed by condensation of compound axis. flowers are sessile or sub-sessile', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'achenial fruit', ' ', 'single fruit, single seeded; may be achene, cypsela, nut or samara', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả bế');
INSERT INTO [Glossary] VALUES (NULL, 'achene', '60', 'dry indehiscent fruit with 1 seed attached to ovary wall at only 1 point', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả dĩnh');
INSERT INTO [Glossary] VALUES (NULL, 'caryposis', '61', 'dry one-seeded fruit in which ovary wall remains joined with seed in a single grain', 'rice, wheat, corn');
INSERT INTO [Glossary] VALUES (NULL, 'cypsela', ' ', '(fruit) pericarp fused with thalamus to form fruit fruit wall. many have pappus (crown of hairs)', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả kiên');
INSERT INTO [Glossary] VALUES (NULL, 'nut', '62', 'single fruit, has a hard woody or sometimes leathery pericarp', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả dực / quả có cánh');
INSERT INTO [Glossary] VALUES (NULL, 'samara', '63', 'one-seeded dry fruit with pericarp grows out into wings', 'maple, ''Hopea''');
INSERT INTO [Glossary] VALUES (NULL, 'capsular fruit', ' ', '= capsule', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả đậu');
INSERT INTO [Glossary] VALUES (NULL, 'pod', '64', 'fruit formed from superior & uniocular ovary of monocarpellary pistil, dehisces dorsally & ventrally', 'peas, beans');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả đại / manh nang');
INSERT INTO [Glossary] VALUES (NULL, 'follicle', '65', '(fruit) like pod, but dehisces from only 1 suture into 2 shells attached together', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'siliqua', ' ', 'capsule dehisces by 4 lines into 2 shells & 1 wall between bearing seeds', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả giác');
INSERT INTO [Glossary] VALUES (NULL, 'silicula', '66', '(fruit) capsule few-seeded, shortened & flattened', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả nang');
INSERT INTO [Glossary] VALUES (NULL, 'capsule', '67', '(fruit) many-seeded & dry, pericarp splits open to expose seeds', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'porous', ' ', '(dehiscence) dehiscence occurs by pores at tip', 'poppy');
INSERT INTO [Glossary] VALUES (NULL, 'dehiscence of teeth', ' ', 'dehiscence by apical teeth', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'tranverse', ' ', '(dehiscence) in form of transverse circular line, causing separation of a lid from top of fruit', 'cock''s comb');
INSERT INTO [Glossary] VALUES (NULL, 'loculicidal', ' ', '(dehiscence) longitudinal, slits occur along midribs (dorsal sutures) of fused carpels', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'septicidal', ' ', '(dehiscence) longitudinal , slits open along middle of septa', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'dseptifragal', ' ', '(dehiscence) longitudinal either loculicidal or septicidal, seeds exposed & attached to central colu', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả mọng / quả phì');
INSERT INTO [Glossary] VALUES (NULL, 'berry', '68', '(fruit) with pericarp divided into epicarp, (soft) mesocarp, endocarp', 'papaya');
INSERT INTO [Glossary] VALUES (NULL, 'baccate', ' ', '= berry', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả hạch / quả nhân cứng');
INSERT INTO [Glossary] VALUES (NULL, 'drupe', '69', '(fruit) generally one-seeded, outer skin thin, middle meat or fibers, inside skin thick covering see', 'mango, coconut');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả hạch / quả nhân cứng');
INSERT INTO [Glossary] VALUES (NULL, 'stone fruit', '70', '= drupe', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả táo');
INSERT INTO [Glossary] VALUES (NULL, 'pome', '71', 'accessory or false fruit, develops from inferior & compound ovary', 'apple');
INSERT INTO [Glossary] VALUES (NULL, 'dehiscence', ' ', 'the way lobes of anther open to expose pollen grains', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đài hoa');
INSERT INTO [Glossary] VALUES (NULL, 'calyx', '72', 'collective of sepals', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'sucker', ' ', 'parasitic roots, penetrate host to absorb host''s nutrients', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đế hoa');
INSERT INTO [Glossary] VALUES (NULL, 'thalamus', '73', 'base of flower proper', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'bộ nhụy');
INSERT INTO [Glossary] VALUES (NULL, 'gynaecium', '74', 'collective of carpels', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'lá noãn / tâm bì');
INSERT INTO [Glossary] VALUES (NULL, 'carpel', '75', 'female organ of flower, consists of ovary, style & stigma', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'núm nhụy / nướm');
INSERT INTO [Glossary] VALUES (NULL, 'stigma', '76', 'terminal portion of pistil, secreting stigma fluid', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'lá bắc');
INSERT INTO [Glossary] VALUES (NULL, 'bract', '77', 'leaf-like growth often on pedicel', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'lá bắc nhỏ');
INSERT INTO [Glossary] VALUES (NULL, 'bractiole', '78', 'small leaf-like sometimes on pedicel', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tràng xếp');
INSERT INTO [Glossary] VALUES (NULL, 'aestivation', '79', 'arrangement of petals in bud condition', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'placentation', ' ', 'arrangement of ovules (placentae)', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hoa tự hình chùm');
INSERT INTO [Glossary] VALUES (NULL, 'raceme', '80', 'rachis along which flowers grow on pedicel, blooming indefinitely from base to apex', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cuống hoa tự');
INSERT INTO [Glossary] VALUES (NULL, 'peduncle', '81', 'axis of entire inflorescence', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'nhị / nhụy');
INSERT INTO [Glossary] VALUES (NULL, 'stamen', '82', 'male organ of flower, consist of filament and anther containing pollen grains', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'chỉ nhị');
INSERT INTO [Glossary] VALUES (NULL, 'filament', '83', 'part of male organ in flower, bearing anther', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'bao phấn');
INSERT INTO [Glossary] VALUES (NULL, 'anther', '84', 'part of male organ in flower, contains pollen grains', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'bilabiate', ' ', 'form of petal having 2 lips', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'gamosepalous', ' ', '(calyx) sepals fused together', 'petunia');
INSERT INTO [Glossary] VALUES (NULL, 'campanulate', ' ', 'bell-shaped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ovule', ' ', 'outgrowth of placenta', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'cymose', ' ', '= cyme', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'uniparous', ' ', '(cyme) terminal bud of main axis develops into a flower, may be helicoid or scorpiod', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'ochrea', ' ', 'stipule forming a sheath covering stem', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'lá bẹ');
INSERT INTO [Glossary] VALUES (NULL, 'stipule', '85', 'lateral outgrowth of leaf base', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'rìa dợn sóng');
INSERT INTO [Glossary] VALUES (NULL, 'repand', '86', '(margin) shallowy undulated', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'sinuate', ' ', '(margin) deeply undulated', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'biserrate', ' ', '(margin) toothed, with each tooth toothed again, e.g. castor', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'dentate', ' ', '(margin) toothed, with teeth directed outwards', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'renate', ' ', '(margin) toothed, with teeth rounded', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'spiny', ' ', '(margin) = spinous, with spines or pickles', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'pistil', ' ', 'free unit of carpel (female organ)', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'sung');
INSERT INTO [Glossary] VALUES (NULL, 'syconium', '87', 'hollow compound fruit with a small spore in genus ''Ficus''', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cánh đài / lá đài');
INSERT INTO [Glossary] VALUES (NULL, 'sepal', '88', ' ', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'bông mo');
INSERT INTO [Glossary] VALUES (NULL, 'spadix', '89', 'spike or catkin of small flowers with peduncle thick & fleshy, usually enclosed in spathe', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cánh tràng');
INSERT INTO [Glossary] VALUES (NULL, 'petal', '90', ' ', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hoa đầu');
INSERT INTO [Glossary] VALUES (NULL, 'capitulum', '91', 'dense cluster of sessile flowers attached to peduncle compressed as a common receptacle', 'asters');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'biệt chu');
INSERT INTO [Glossary] VALUES (NULL, 'dioecious', '92', 'having male flowers on one plant, female flowers on another plant', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'đồng chu');
INSERT INTO [Glossary] VALUES (NULL, 'monoecious', '93', 'having separate male flowers and female flowers on same plant', 'corn');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'chùm kép');
INSERT INTO [Glossary] VALUES (NULL, 'raceme, compound', '94', 'axis branching, each branch bearing flowers', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cụm hoa / hoa tự');
INSERT INTO [Glossary] VALUES (NULL, 'inflorescence', '95', 'the arrangement of flowers on an axis', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cuống hoa');
INSERT INTO [Glossary] VALUES (NULL, 'pedicel', '96', 'the stalk of a single flower', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'khí khổng');
INSERT INTO [Glossary] VALUES (NULL, 'stoma', '97', 'a microscopic opening in the epidermis, serving for gaseous exchange', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phế căn');
INSERT INTO [Glossary] VALUES (NULL, 'pneumatophore', '98', 'porous, woody specialized branch growing upright into air from buried roots', 'Rhizophora');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'quả kiên / quả giẻ');
INSERT INTO [Glossary] VALUES (NULL, 'acorn', '99', '(fruit) like those of chestnut', 'family ''Fagaceae''');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'xim đơn / xim co');
INSERT INTO [Glossary] VALUES (NULL, 'glomerule', '100', 'compact cyme with dense flowers', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'tổng bao');
INSERT INTO [Glossary] VALUES (NULL, 'involucel', '101', 'secondary involucre, ring of bracts at base of each segment of a cluster', 'asters');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phiến hình bầu dục');
INSERT INTO [Glossary] VALUES (NULL, 'broadly elliptical', '102', '(lamina) apex and base tapering in the same way, widest point at middle', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'mo');
INSERT INTO [Glossary] VALUES (NULL, 'spathe', '103', 'a large leaf-like part enclosing a cluster', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cựa');
INSERT INTO [Glossary] VALUES (NULL, 'calcar', '104', 'downward extended, hollow part of calyx or corolla', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hoa tự hình chùy');
INSERT INTO [Glossary] VALUES (NULL, 'panicle', '105', '= compound raceme, a raceme bearing smaller racemes', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'bầu / bầu nhụy');
INSERT INTO [Glossary] VALUES (NULL, 'ovary', '106', ' ', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'vòi nhụy');
INSERT INTO [Glossary] VALUES (NULL, 'style', '107', 'the contricted part above ovary', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'bao hoa');
INSERT INTO [Glossary] VALUES (NULL, 'perianth', '108', 'outer envelope of flower, formed by calyx and corolla', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'xếp vặn');
INSERT INTO [Glossary] VALUES (NULL, 'convolute', '109', '(petals) rolled in spiral form with the coils falling one upon another', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'xếp van / xếp đều');
INSERT INTO [Glossary] VALUES (NULL, 'valvate', '110', '(petals) meeting without overlapping', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'cánh kiến');
INSERT INTO [Glossary] VALUES (NULL, 'lac insect', '111', 'which produces sticklac for industry, as medicine', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'carinate', ' ', 'having a ridge down the middle; keel-shaped', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'fimbriate', ' ', 'with a fringe of hairs, fibers', ' ');
INSERT INTO [Glossary] VALUES (NULL, 'rugose', ' ', 'having wrinkles; ridged; corrugated', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'phiến lá');
INSERT INTO [Glossary] VALUES (NULL, 'lamina', '112', ' ', ' ');
INSERT INTO [Locales] VALUES (NULL, 'vn', 'hình soan');
INSERT INTO [Glossary] VALUES (NULL, 'oval', '113', ' ', ' ');
